In [79]:
import pandas as pd
import numpy as np
obj=pd.Series([1,2,3,4,5])  # index it will display
obj

0    1
1    2
2    3
3    4
4    5
dtype: int64

# Introduction to pandas Data Structures
#Series

In [80]:
obj.values  # element of that obj

array([1, 2, 3, 4, 5])

In [81]:
obj.index  # range from which it start, stop and step

RangeIndex(start=0, stop=5, step=1)

In [82]:
obj2=pd.Series([1,2,3,-4,5], index=['d','a','c','f','h'])  
obj2

d    1
a    2
c    3
f   -4
h    5
dtype: int64

In [83]:

obj2.index

Index(['d', 'a', 'c', 'f', 'h'], dtype='object')

In [84]:
 obj2['a']  # corresponding index value

2

In [85]:
obj2[['d','c','h']] # it treats as indices even they are strings

d    1
c    3
h    5
dtype: int64

In [86]:
obj2[obj2>0]  # prints values greather than zero

d    1
a    2
c    3
h    5
dtype: int64

In [87]:
obj2 * 2  # specified operation it perform

d     2
a     4
c     6
f    -8
h    10
dtype: int64

In [88]:
np.exp(obj2)  

d      2.718282
a      7.389056
c     20.085537
f      0.018316
h    148.413159
dtype: float64

In [89]:
'a' in obj2  # index 'a' exist s1 

True

In [90]:
'v' in obj2 # doesn't exist

False

In [91]:

sdata={'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3=pd.Series(sdata)  # dict passing in Series it display data in tabular form
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [92]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4=pd.Series(sdata,index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [93]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [94]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [95]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [96]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [97]:
obj3+obj4 


California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [98]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [99]:
obj4.name='population'
obj4.index.name='state'  # state column nane labeled
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [100]:
obj

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [101]:
obj.index=['Bob', 'Steve', 'Jeff', 'Ryan','mike']  # Index changed


In [102]:
obj

Bob      1
Steve    2
Jeff     3
Ryan     4
mike     5
dtype: int64

# DataFrame
DF rectangular table of data and contains ab ordered collection of columns .DataFrames has both row and column index.It is treated as dict of Series all sharing same indes.Data is stored as one or more two dimensiona block rather than list, dict.

In [103]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)

In [104]:
frame  #DF displays data in tabular form, keys columns label

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [105]:
pd.DataFrame(data,columns=['year','state','pop'])# changing the column order

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [106]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'], index=['one', 'two', 'three', 'four',
'five', 'six'])

In [107]:
frame2  # new column added with indecies One to Six

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [108]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [109]:
frame2['state'] # displays state columns values

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [110]:
frame2['year']

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [111]:
frame2.loc['three']


year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [112]:
frame2['debt']=23.5
frame2  # all debt values are assigned 23.5

year   state  pop  debt
one    2000    Ohio  1.5  23.5
two    2001    Ohio  1.7  23.5
three  2002    Ohio  3.6  23.5
four   2001  Nevada  2.4  23.5
five   2002  Nevada  2.9  23.5
six    2003  Nevada  3.2  23.5

In [113]:
frame2['debt']=np.arange(6.)  # number of rows put it in asending order

In [114]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [115]:
val=pd.Series([-1.2,-1.6,-1.8],index=['two','four','five'])
frame2['debt']=val# assigning val to debt column for those index
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.6
five   2002  Nevada  2.9  -1.8
six    2003  Nevada  3.2   NaN

In [116]:
frame2['eastern']=frame2.state == 'Ohio'  # for ohio state we are settig eastern True
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.6    False
five   2002  Nevada  2.9  -1.8    False
six    2003  Nevada  3.2   NaN    False

In [117]:
del frame2['eastern']  # delete eastern clomun 

In [118]:
frame2.columns   

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [119]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.6
five   2002  Nevada  2.9  -1.8
six    2003  Nevada  3.2   NaN

In [120]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
 'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}


In [121]:
frame3=pd.DataFrame(pop)  #pop dict adding to frame3 dataframe
frame3  

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [122]:
frame3.T  # Intercahnge columns and rows

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [123]:
pd.DataFrame(pop,index=[2001,2002,2003]) # setting index back 


Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [124]:
pdata = {'Ohio': frame3['Ohio'][:-1], 'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [125]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [126]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.6],
       [2002, 'Nevada', 2.9, -1.8],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

# Index objects


In [127]:
obj=pd.Series(range(3),index=['a','b','c'])
index=obj.index
index
                              

Index(['a', 'b', 'c'], dtype='object')

In [128]:
index[1:] # from 1, index ob are immutable and can't be modidied by user


Index(['b', 'c'], dtype='object')

In [129]:
#index[1]='d' # type error we can;'t modify thr index'

In [130]:
labels=pd.Index(np.arange(3)) # column 0 to 2

In [131]:
labels

Int64Index([0, 1, 2], dtype='int64')

In [132]:
obj2=pd.Series([1.5,-2.4,0],index=labels)
obj2

0    1.5
1   -2.4
2    0.0
dtype: float64

In [133]:
obj2.index is labels


True

In [134]:
frame3


Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [135]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object')

In [136]:
'Ohio' in frame3.columns

True

In [137]:
2003 in frame3.index

False

In [138]:
dup_labels = pd.Index(['foo', 'foo', 'bar', 'bar'])
dup_labels

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

# Reindexing

In [139]:
obj = pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [140]:
 obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e']) # reassigned index to obj2
obj2
    

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [141]:
 obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: object

In [142]:
obj3.reindex(range(6), method='ffill') # 0 to 5

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [143]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)), index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame # reshape the frame 3 cross 3

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [144]:
frame2 = frame.reindex(['a', 'b', 'c', 'd'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [145]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)  #frame reassigning column

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [146]:
frame.loc[['a', 'b', 'c', 'd'], states]  
# row b should gets added up 


KeyError: "['b'] not in index"

# Dropping Entries from an Axis

In [147]:
obj = pd.Series(np.arange(5.), index=['a', 'b', 'c', 'd', 'e'])

In [148]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [149]:
new_obj=obj.drop('c') # removed c row

In [150]:
new_obj

a    0.0
b    1.0
d    3.0
e    4.0
dtype: float64

In [151]:
obj.drop(['d', 'c'])

a    0.0
b    1.0
e    4.0
dtype: float64

In [152]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [153]:
data.drop(['Colorado', 'Ohio']) # drop index/row if given in list []


one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [154]:

data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [155]:
data.drop('two', axis=1) # axis means 

one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [156]:
data.drop(['two', 'four'], axis='columns')   

one  three
Ohio        0      2
Colorado    4      6
Utah        8     10
New York   12     14

#Be careful with the inplace, as it destroys any data that is dropped.
#Many functions, like drop, which modify the size or shape of a Series or DataFrame, can manipulate an object in-place without returning a new object:


In [157]:
obj.drop('b', inplace=True)   # as I already destroyed c now its allowing to use c
obj

a    0.0
c    2.0
d    3.0
e    4.0
dtype: float64

# Indexing, Selection, and Filtering

In [158]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [159]:
obj['b']

1.0

In [160]:
obj[1]

1.0

In [161]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [162]:
 obj[['b', 'a', 'd']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [163]:
obj[[1,3]] # display 1,3

b    1.0
d    3.0
dtype: float64

In [164]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [165]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [166]:
obj['b':'c'] = 5

In [167]:
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [168]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [169]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int64

In [170]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [171]:
data[:2]  # 0,1
  

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [172]:
data[data['three']>5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [173]:
data<5 # 1st 5 elements

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [174]:

data[data <5] =0  # 1st 5 elements =0
data 

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

# Selection with loc and iloc
For DataFrame label-indexing on the rows, I introduce the special indexing operators loc and iloc. They enable you to select a subset of the rows and columns from a DataFrame with NumPy-like notation using either axis labels (loc) or integers (iloc)

In [175]:
data.loc['Colorado', ['two', 'three']] # that location element usiong name 

two      5
three    6
Name: Colorado, dtype: int64

In [176]:
 data.iloc[2, [3, 0, 1]] # using integers

four    11
one      8
two      9
Name: Utah, dtype: int64

In [177]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int64

In [178]:
data.iloc[[1, 2], [3, 0, 1]]

four  one  two
Colorado     7    0    5
Utah        11    8    9

In [179]:
data.loc[:'Utah', 'two'] # upto Utah

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int64

In [180]:
data.iloc[:, :3][data.three > 5] # not that clear

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

# Integer Indexes

In [181]:
ser = pd.Series(np.arange(3.))

In [182]:
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [183]:
 ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])

In [184]:
ser2[-1]

2.0

In [185]:
ser[:1]

0    0.0
dtype: float64

In [186]:
ser.loc[:1]

0    0.0
1    1.0
dtype: float64

In [187]:
ser.iloc[:1]

0    0.0
dtype: float64


# Arithmetic and Data Alignment

In [188]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])

In [189]:
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1],
               index=['a', 'c', 'e', 'f', 'g'])

In [190]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [191]:
s2


a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [192]:
s1+s2  # if only have other doesn;t then NAN

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [193]:

 df1= pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list('bcd'), index=['Ohio', 'Texas', 'Colorado'])

In [194]:
df2= pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [195]:
df1

b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [196]:
df2


b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [197]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [198]:
 df1= pd.DataFrame({'A': [1, 2]})

In [199]:
df2=pd.DataFrame({'B':[3,4]})

In [200]:
df1


A
0  1
1  2

In [201]:
df2

B
0  3
1  4

In [202]:
df1-df2


A   B
0 NaN NaN
1 NaN NaN


# Arithmetic methods with fill values

In [203]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))

In [204]:
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))



In [205]:
df2.loc[1,'b']=np.nan


In [206]:
df1


a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0

In [207]:
df2

a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [208]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [209]:
1/df1

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [210]:
df1.rdiv(1)

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [211]:
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [212]:

arr= np.arange(12.).reshape((3, 4))

In [213]:
arr


array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [214]:
arr[0]

array([0., 1., 2., 3.])

In [215]:
arr -arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

# Function Application and Mapping

In [216]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list('bde'),
index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [217]:
series=frame.iloc[0]

In [218]:
frame


b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [219]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [220]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [221]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])

In [222]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [223]:
series3 = frame['d']

In [224]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [225]:
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [226]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [227]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [228]:
frame


b         d         e
Utah    2.185282  0.001462 -0.119811
Ohio    1.629160 -0.808784 -0.177541
Texas  -0.871660 -0.184905  1.484546
Oregon -0.629751 -0.947723 -2.245701

In [229]:
np.abs(frame)

b         d         e
Utah    2.185282  0.001462  0.119811
Ohio    1.629160  0.808784  0.177541
Texas   0.871660  0.184905  1.484546
Oregon  0.629751  0.947723  2.245701

In [230]:

f=lambda x:x.max() - x.min()

In [231]:
frame.apply(f)

b    3.056943
d    0.949184
e    3.730247
dtype: float64

In [232]:
frame.apply(f,axis='columns')

Utah      2.305093
Ohio      2.437943
Texas     2.356206
Oregon    1.615951
dtype: float64

In [233]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])


In [234]:
frame.apply(f)

b         d         e
min -0.871660 -0.947723 -2.245701
max  2.185282  0.001462  1.484546

In [235]:
format = lambda x: '%.2f' % x

In [236]:
frame.applymap(format)

b      d      e
Utah     2.19   0.00  -0.12
Ohio     1.63  -0.81  -0.18
Texas   -0.87  -0.18   1.48
Oregon  -0.63  -0.95  -2.25

In [237]:

frame['e'].map(format)

Utah      -0.12
Ohio      -0.18
Texas      1.48
Oregon    -2.25
Name: e, dtype: object

# Sorting and Ranking
Sorting a dataset by some criterion is another important built-in operation. To sort lexicographically by row or column index, use the sort_index method, which returns a new, sorted object:

In [238]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])

In [239]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [240]:
frame=pd.DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'],
columns=['d', 'a', 'b', 'c'])

In [241]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [242]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [243]:
frame.sort_index(axis=1, ascending=False) # from column 1 decending 

d  c  b  a
three  0  3  2  1
one    4  7  6  5

In [244]:
obj = pd.Series([4, 7, -3, 2])

In [245]:
obj.sort_values()

2   -3
3    2
0    4
1    7
dtype: int64

In [246]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])

In [247]:
obj.sort_values()  # sort basis of values

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [248]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})


In [249]:
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [250]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [251]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

In [252]:
obj = pd.Series([7, -5, 7, 4, 2, 0, 4])

In [253]:
obj.rank() # assign mean to all values 

0    6.5
1    1.0
2    6.5
3    4.5
4    3.0
5    2.0
6    4.5
dtype: float64

In [254]:
obj.rank(method='first')

0    6.0
1    1.0
2    7.0
3    4.0
4    3.0
5    2.0
6    5.0
dtype: float64

In [255]:
obj.rank(ascending=False, method='max')

0    2.0
1    7.0
2    2.0
3    4.0
4    5.0
5    6.0
6    4.0
dtype: float64

In [256]:
frame = pd.DataFrame({'b': [4.3, 7, -3, 2], 'a': [0, 1, 0, 1],
 'c':[-2, 5, 8, -2.5]})

In [257]:
frame

b  a    c
0  4.3  0 -2.0
1  7.0  1  5.0
2 -3.0  0  8.0
3  2.0  1 -2.5

In [258]:
frame.rank(axis='columns')

b    a    c
0  3.0  2.0  1.0
1  3.0  1.0  2.0
2  1.0  2.0  3.0
3  3.0  2.0  1.0

# Axis Indexes with Duplicate Labels

In [259]:
obj = pd.Series(range(5), index=['a', 'a', 'b', 'b', 'c'])

In [260]:
obj

a    0
a    1
b    2
b    3
c    4
dtype: int64

In [261]:
obj.index.is_unique

False

In [262]:
obj['a']

a    0
a    1
dtype: int64

In [263]:
obj['c']

4

In [264]:
df = pd.DataFrame(np.random.randn(4, 3), index=['a', 'a', 'b', 'b'])

In [265]:

df

0         1         2
a  0.920977  0.219769  1.111205
a  0.159943  0.860390  0.545668
b  0.116317 -1.329071 -0.900189
b -1.162775 -0.381186 -0.061429

In [266]:
df.loc['b']

0         1         2
b  0.116317 -1.329071 -0.900189
b -1.162775 -0.381186 -0.061429

In [267]:
df= pd.DataFrame([[1.4, np.nan], [7.1, -4.5], [np.nan, np.nan], [0.75, -1.3]],
               index=['a', 'b', 'c', 'd'],
               columns=['one', 'two'])

In [268]:
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [269]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [270]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [271]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [272]:
df.idxmax()

one    b
two    d
dtype: object

In [273]:
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [274]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [275]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)

In [276]:
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object

In [277]:
!pip install pandas-datareader


DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621


In [278]:

import pandas_datareader.data as web
all_data= {ticker: web.get_data_yahoo(ticker)
for ticker in ['AAPL', 'IBM', 'MSFT', 'GOOG']}

In [279]:
price = pd.DataFrame({ticker: data['Adj Close']
                     for ticker, data in all_data.items()})


In [280]:
volume = pd.DataFrame({ticker: data['Volume']  for ticker, data in all_data.items()})

In [281]:
returns =price.pct_change()

In [282]:
returns.tail()

AAPL       IBM      MSFT      GOOG
Date                                              
2022-03-29  0.019134  0.003575  0.015159  0.009158
2022-03-30 -0.006650  0.001440 -0.004914 -0.004227
2022-03-31 -0.017776 -0.015969 -0.017683 -0.020996
2022-04-01 -0.001718  0.001000  0.003600  0.007522
2022-04-01  0.000000  0.000000  0.000000  0.000000

In [283]:
returns['MSFT'].corr(returns['IBM'])

0.48168905224246805

In [284]:
 returns['MSFT'].cov(returns['IBM'])

0.00014403269798624432

In [285]:
 returns.MSFT.corr(returns.IBM)
    

0.48168905224246805

In [286]:
returns.corr()

AAPL       IBM      MSFT      GOOG
AAPL  1.000000  0.429602  0.746059  0.667216
IBM   0.429602  1.000000  0.481689  0.455943
MSFT  0.746059  0.481689  1.000000  0.786235
GOOG  0.667216  0.455943  0.786235  1.000000

In [287]:
returns.cov()

AAPL       IBM      MSFT      GOOG
AAPL  0.000381  0.000140  0.000260  0.000229
IBM   0.000140  0.000281  0.000144  0.000135
MSFT  0.000260  0.000144  0.000318  0.000247
GOOG  0.000229  0.000135  0.000247  0.000310

In [288]:
returns.corrwith(returns.IBM)

AAPL    0.429602
IBM     1.000000
MSFT    0.481689
GOOG    0.455943
dtype: float64

In [289]:
returns.corrwith(volume)

AAPL   -0.082661
IBM    -0.129513
MSFT   -0.068489
GOOG   -0.091678
dtype: float64

In [290]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])

In [291]:
uniques = obj.unique()

In [292]:
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

In [293]:
obj.value_counts()

c    3
a    3
b    2
d    1
dtype: int64

In [294]:

pd.value_counts(obj.values, sort=False)

c    3
a    3
d    1
b    2
dtype: int64

In [295]:
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [296]:
mask = obj.isin(['b', 'c'])


In [297]:
mask


0     True
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [298]:
obj[mask]

0    c
5    b
6    b
7    c
8    c
dtype: object

In [299]:
to_match = pd.Series(['c', 'a', 'b', 'b', 'c', 'a'])


In [300]:
unique_vals = pd.Series(['c', 'b', 'a'])


In [301]:
pd.Index(unique_vals).get_indexer(to_match)

array([0, 2, 1, 1, 0, 2])

In [302]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4], 'Qu2': [2, 3, 1, 2, 3],
                     'Qu3': [1, 5, 2, 4, 4]})

In [303]:
data


Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [304]:
result = data.apply(pd.value_counts).fillna(0)

In [305]:
result

Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0